#!/bin/bash

PACKAGE_INFO_SHOW=true

#NGINX_MAKE=true
#NGINX_INSTALL=true
#NGINX_UPDATE_CONFIG=true
#NGINX_UPDATE_SERVICE=true
#NGINX_RESTART=true

MONGODB_INSTALL=true
MONGODB_UPDATE_CONFIG=true
MONGODB_UPDATE_SERVICE=true
MONGODB_RESTART=true

source deploy.sh