Reading package lists...
Building dependency tree...
Reading state information...
gcc is already the newest version (4:9.3.0-1ubuntu2).
make is already the newest version (4.2.1-1.2).
curl is already the newest version (7.68.0-1ubuntu2.11).
wget is already the newest version (1.20.3-1ubuntu2).
The following packages were automatically installed and are no longer required:
  apache2-data libodbc1 ssl-cert
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 655 not upgraded.
