#!/bin/bash

PACKAGE_INFO_SHOW=true

#NGINX_INSTALL=true
#NGINX_UPDATE_CONFIG=true
#NGINX_UPDATE_SERVICE=true
NGINX_RESTART=true

#MONGOD_INSTALL=true
#MONGOD_UPDATE_CONFIG=true
#MONGOD_UPDATE_SERVICE=true
MONGOD_RESTART=true

#OPENSSL_BUILD=true
#LDAP_CONF_OPENSS=true
#LDAP_INSTALL=true
#LDAP_UPDATE_CONFIG=true
#LDAP_UPDATE_SERVICE=true
LDAP_RESTART=true
#LDAP_LOAD_DEMO=true
source deploy.sh