#!/bin/bash

PACKAGE_INFO_SHOW=false

#NGINX_UPDATE_CONFIG=true
#NGINX_UPDATE_SERVICE=true
NGINX_RESTART=true

#MONGODB_UPDATE_CONFIG=true
#MONGODB_UPDATE_SERVICE=true
#MONGODB_RESTART=true
#
#LDAP_UPDATE_CONFIG=true
#LDAP_UPDATE_SERVICE=true
LDAP_RESTART=true

source deploy.sh