#!/bin/bash

PACKAGE_INFO_SHOW=false

NGINX_UPDATE_CONFIG=true
#NGINX_UPDATE_SERVICE=true
#NGINX_RESTART=true

#MONGOD_UPDATE_CONFIG=true
#MONGOD_UPDATE_SERVICE=true
#MONGOD_RESTART=true
#
#LDAP_UPDATE_CONFIG=true
#LDAP_UPDATE_SERVICE=true
#LDAP_RESTART=true

source setup.sh